name: track-eval
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.1.1
  - cycler=0.12.1
  - cython=3.0.11
  - exceptiongroup=1.2.2
  - fonttools=4.53.1
  - freetype=2.12.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-resources=6.4.3
  - importlib_resources=6.4.3
  - iniconfig=2.0.0
  - kiwisolver=1.4.5
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=18.1.8
  - libdeflate=1.21
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.25
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - munkres=1.1.4
  - ncurses=6.5
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.1
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - pooch=1.8.2
  - pthread-stubs=0.4
  - pycocotools=2.0.7
  - pycparser=2.22
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - pytest=8.3.2
  - python=3.8.19
  - python-dateutil=2.9.0
  - python_abi=3.8
  - readline=8.2
  - requests=2.32.3
  - scipy=1.10.1
  - setuptools=72.2.0
  - six=1.16.0
  - tabulate=0.9.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - wheel=0.44.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zipp=3.20.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - imageio==2.35.1
      - lazy-loader==0.4
      - networkx==3.1
      - numpy==1.21.6
      - opencv-python==4.10.0.84
      - pywavelets==1.4.1
      - scikit-image==0.21.0
      - tifffile==2023.7.10
